site: HgTx Studio
url: https://hgtx.net
baseurl: 

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed
  silence_deprecations:
    - import

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-email-protect

pagination:
  enabled: true
  per_page: 6
  permalink: '/blog/page/:num/'
  sort_field: 'date'
  sort_reverse: true

